#!/bin/sh
#
# Copyright (c) 2025-2026 Jacob R. Edwards <jacob@jacobedwards.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

log() {
	echo "$(basename "$0"): $@" 1>&2
}

usage() {
	echo "usage: $(basename "$0") [-d dir] [repo ...]" 1>&2
	exit 1
}

gitls() {
	git ls-tree --full-tree -r HEAD
}

gitman() {
	s="${1##*.}"
	sprefix="$2"/man$s
	mkdir -p "$sprefix"
	name="$(basename "$1")"
	path="$sprefix"/"$name"
	git show HEAD:"$1" > "$path"
	echo "$path"
}

set -e

case "$(uname)" in
(OpenBSD) makewhatis() { command makewhatis -d "$prefix" "$@" ;} ;;
esac

prefix=.
while test $# -gt 0
do
	case "$1" in
	(-d) prefix="${2:?-d requires an argument}"; shift ;;
	(-*) log "$1: Invalid option"; usage ;;
	(--) shift; break ;;
	(*) break ;;
	esac
	shift
done

pages="$(
	for d in "${@:-"${GIT_DIR:?No repositories given}"}"
	do
		GIT_DIR="$d"
		export GIT_DIR
		for f in $(gitls | awk '/\.[0-9]$/ { print $NF }')
		do
			gitman "$f" "$prefix"
		done
	done
)"
IFS='
'
makewhatis $pages
echo "$pages"
