./"
./" Copyright (c) 2025-2026 Jacob Edwards <jacob@jacobedwards.org>
./"
./" Permission to use, copy, modify, and distribute this software for any
./" purpose with or without fee is hereby granted, provided that the above
./" copyright notice and this permission notice appear in all copies.
./"
./" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIE
./" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
./" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
./" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
./" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
./" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
./" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
./"
.Dd October 19, 2025
.Dt GITSRV.CONF 5
.Os
.Sh NAME
.Nm gitsrv.conf
.Nd gitsrv configuration file
.Sh DESCRIPTION
The
.Nm
configuration file contains various options for
.Xr gitsrv 1 .
Options are specified one per line, with values separated by
whitespace. Empty lines or lines beginning with hash
.Pq Qq #
are ignored.
.Pp
The options are listed below:
.Bl -tag -width Ds
.It Ic stagit Ar enable
Set
.Ar enable
to
.Qq true
to enable stagit page generation. See
.Xr stagit-hook.conf 5
for stagit configuration.
.It Ic distdir Ar directory
Enables archive creation for tags and writes archive files to
.Ar directory .
.It Ic distfmt Ar format
Sets the archive format for
.Xr gitdist 1 .
(See its
.Fl f
flag.)
.It Ic mandir Ar directory 
Enable manpage exports with
.Xr gitman
and configure the base directory.
.It Ic ghtoken Ar token
Enable GitHub mirroring with
.Xr github-mirror 1
and use
.Ar token
as the PAT.
.It Ic pubfile Ar filename
Specify the file that determines if the repository is public or not. Default is
.Pa git-daemon-export-ok .
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/gitsrv.conf
Contains configuration data for
.Xr gitsrv 1 .
.El
.Sh EXAMPLES
Here is an example
.Pa /etc/gitsrv.conf :
.Bd -offset indent -literal
baseurl https://example.com/git
basedir /var/www/htdocs/example.com/git
hasfile git-daemon-export-ok
.Ed
.Sh SEE ALSO
.Xr stagit 1 ,
.Xr gitsrv 1 ,
.Xr stagit-index 1
.Sh AUTHORS
.An Jacob R. Edwards Aq Mt jacob@jacobedwards.org
